name: code coverage

on:
  push:
    branches:
      - main

#  pull_request:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#    - name: Build with Maven
#      run: mvn -X clean test install jacoco:report
    
    # check git environment variables
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    # detect changes
    - name: find changed directories
      run: |
        if [ $GITHUB_BASE_REF ]; then
          # Pull Request
          echo "in pull request:"
          echo $GITHUB_BASE_REF
          git fetch origin $GITHUB_BASE_REF --depth=1
          echo "CHANGED_DIR=$( git diff --name-only ${{ github.event.before }} ${{ github.event.pull_request.head.sha }}  | cut -d/ -f1 | sort -u | sed -z 's/\n/,/g;s/^/[/;s/,$/]/;s/$/\n/')" >> ${GITHUB_ENV}
        else
          # Push
          echo "in push"
          git fetch origin ${{ github.event.before }} --depth=1
          echo "CHANGED_DIR=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA  | cut -d/ -f1 | sort -u | sed -z 's/\n/,/g;s/^/[/;s/,$/]/;s/$/\n/')" >> ${GITHUB_ENV}
        fi
        
        echo $CHANGED_DIR
        echo github.event.pull_request.base.sha: ${{ github.event.pull_request.base.sha }}
        echo github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}
        echo github.event.before: ${{ github.event.before }}
        echo GITHUB_SHA: $GITHUB_SHA

      # Runs a set of commands using the runners shelll
      
    - name: Run a multi-line script
      run: |
          echo ${{ env.CHANGED_DIR }}
          echo "${{ github.event.pull_request.base.sha }}"
          echo "${{ github.event.inputs.version }}"
          pwd
          ls -l
          

#          echo setup token
#          export CODACY_PROJECT_TOKEN=a9d3fdfb91534f119d608e1d8d54b40b
#          echo run upload command
#          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf '-r %p ')
#          echo report command execution complete
#
#          echo "${{ github.sha }}"
#          echo "--------------------"
#          echo "$(git diff --name-only --diff-filter=ACMRT --line-prefix=`git rev-parse --show-toplevel`/ ${{ github.event.pull_request.base.sha }} ${{ github.sha }}|xargs)"
