name: workflow with list
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: print all
        env:
          JVM_PROJECTS: |
            mod1
            mod2
        run: |
          pwd
          sub_modules=($( mvn help:evaluate -Dexpression=project.modules -q -DforceStdout | tail -n +2 | head -n -1 | sed 's/\s*<.*>\(.*\)<.*>/\1/'))
          printf "${sub_modules[0]} "
          printf "${sub_modules[1]} "
          for module in "${sub_modules[@]}"
          do
            echo "Module: $module"
            echo "=============="
            #mvn -f $module/pom.xml clean
            echo "=============================================================="
            #ls $module/target/site/apidocs/
          done
          
          # mvn compile
