name: workflow with list
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: print all
        env:
          JVM_PROJECTS: |
            mod1
            mod2
        run: |
          . ./automation/javadoc-script.sh
          
          # mvn compile
