name: workflow with list
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: print all
        env:
          JVM_PROJECTS: |
            mod1
            mod2
        run: |
          pwd
          pwd
          echo $JVM_PROJECTS
          for module in $JVM_PROJECTS
          do
            echo "Module: $module"
            echo "=============="
            mvn -f $module/pom.xml javadoc:javadoc
            ls @module/target/site/apidocs/
          done
          # mvn compile
